Repository teamCoSaIn/trilo-be, pull requests merged in 2023-05, with the labels that each got.

#49 [TRL-158] feat: 일정 수정 API 구현
  src/main/java/com/cosain/trilo/trip/command/application/command/ScheduleUpdateCommand.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoScheduleUpdateAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/ScheduleNotFoundException.java
  src/main/java/com/cosain/trilo/trip/command/application/service/ScheduleUpdateService.java
  src/main/java/com/cosain/trilo/trip/command/application/usecase/ScheduleUpdateUseCase.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Schedule.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/ScheduleRepository.java
  src/main/java/com/cosain/trilo/trip/command/presentation/schedule/ScheduleUpdateController.java
  src/main/java/com/cosain/trilo/trip/command/presentation/schedule/dto/ScheduleUpdateRequest.java
  src/main/java/com/cosain/trilo/trip/command/presentation/schedule/dto/ScheduleUpdateResponse.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/schedule/ScheduleUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/ScheduleRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/schedule/ScheduleUpdateControllerTest.java
Labels: ⚙️ FEAT, 💯 TEST

#52 [TRL-229] feat: 일정 순서 필드 추가 및 임시보관함 설계
  src/main/java/com/cosain/trilo/trip/command/application/service/ScheduleCreateService.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Day.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Schedule.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Trip.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/ScheduleIndexRangeException.java
  src/main/java/com/cosain/trilo/trip/command/domain/vo/ScheduleIndex.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/schedule/ScheduleCreateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/ScheduleRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/TripRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/vo/ScheduleIndexTest.java
Labels: ⚙️ FEAT

#53 [TRL-117] feat: 여행 단건 조회 API 구현
  build.gradle
  src/main/java/com/cosain/trilo/config/QueryDslConfig.java
  src/main/java/com/cosain/trilo/trip/query/application/exception/NoTripDetailSearchAuthorityException.java
  src/main/java/com/cosain/trilo/trip/query/application/exception/TripNotFoundException.java
  src/main/java/com/cosain/trilo/trip/query/application/service/TripDetailSearchService.java
  src/main/java/com/cosain/trilo/trip/query/application/usecase/TripDetailSearchUseCase.java
  src/main/java/com/cosain/trilo/trip/query/domain/repository/TripQueryRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/dto/TripDetail.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/TripQueryDslRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/TripQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/SingleTripQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/dto/TripDetailResponse.java
  src/test/java/com/cosain/trilo/config/QueryDslConfig.java
  src/test/java/com/cosain/trilo/unit/trip/query/application/TripDetailSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/infra/repository/TripQueryRepositoryImplTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/trip/SingleTripQueryControllerTest.java
Labels: ⚙️ FEAT, 💯 TEST

#55 [TRL-234] refactor: 여행 조회 Repository 의존관계 변경
  src/main/java/com/cosain/trilo/config/JpaConfig.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/TripQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/jpa/TripQueryJpaRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/jpa/TripQueryJpaRepositoryCustom.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/jpa/TripQueryJpaRepositoryImpl.java
  src/test/java/com/cosain/trilo/support/RepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/DayRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/ScheduleRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/TripRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/infra/repository/TripQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/user/infra/UserRepositoryTest.java
Labels: 🚀 REFACTOR, 💯 TEST

#54 [TRL-233] feat: 일정 생성 기능 확장(임시보관함 적용, 순서 부여)
  src/main/java/com/cosain/trilo/trip/command/application/service/ScheduleCreateService.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Day.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Schedule.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Trip.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/InvalidTripDayException.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/ScheduleRepository.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/schedule/ScheduleCreateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/entity/TripTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/ScheduleRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/TripRepositoryTest.java
Labels: ⚙️ FEAT, 🚀 REFACTOR

#56 [TRL-118] feat: 특정 사용자 여행 목록 API 구현
  .gitignore
  src/main/java/com/cosain/trilo/trip/query/application/exception/TripperNotFoundException.java
  src/main/java/com/cosain/trilo/trip/query/application/service/TripListSearchService.java
  src/main/java/com/cosain/trilo/trip/query/application/usecase/TripListSearchUseCase.java
  src/main/java/com/cosain/trilo/trip/query/domain/repository/TripQueryRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/TripQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/jpa/TripQueryJpaRepositoryCustom.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/jpa/TripQueryJpaRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/TripperTripListQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/dto/TripPageResponse.java
  src/test/java/com/cosain/trilo/unit/trip/query/application/TripListSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/infra/repository/TripQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/trip/TripperTripListQueryControllerTest.java
Labels: ⚙️ FEAT, 💯 TEST

#58 [TRL-153] feat: 일정 단건 조회 API 구현
  src/main/java/com/cosain/trilo/config/JpaConfig.java
  src/main/java/com/cosain/trilo/trip/query/application/dto/ScheduleResult.java
  src/main/java/com/cosain/trilo/trip/query/application/exception/ScheduleNotFoundException.java
  src/main/java/com/cosain/trilo/trip/query/application/service/ScheduleDetailSearchService.java
  src/main/java/com/cosain/trilo/trip/query/application/usecase/ScheduleDetailSearchUseCase.java
  src/main/java/com/cosain/trilo/trip/query/domain/dto/ScheduleDto.java
  src/main/java/com/cosain/trilo/trip/query/domain/repository/ScheduleQueryRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/dto/ScheduleDetail.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/schedule/ScheduleQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/schedule/jpa/ScheduleQueryJpaRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/schedule/jpa/ScheduleQueryJpaRepositoryCustom.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/schedule/jpa/ScheduleQueryJpaRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/presentation/schedule/SingleScheduleQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/schedule/dto/ScheduleDetailResponse.java
  src/test/java/com/cosain/trilo/support/RepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/application/ScheduleDetailSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/infra/repository/ScheduleQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/schedule/SingleScheduleQueryControllerTest.java
Labels: ⚙️ FEAT, 💯 TEST

#57 [TRL-213] feat: 일정 이동 API 구현
  src/main/java/com/cosain/trilo/trip/command/application/command/ScheduleMoveCommand.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoScheduleMoveAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/result/ScheduleMoveResult.java
  src/main/java/com/cosain/trilo/trip/command/application/service/ScheduleMoveService.java
  src/main/java/com/cosain/trilo/trip/command/application/usecase/ScheduleMoveUseCase.java
  src/main/java/com/cosain/trilo/trip/command/domain/dto/ScheduleMoveDto.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Day.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Schedule.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Trip.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/InvalidScheduleMoveTargetOrderException.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/MidScheduleIndexConflictException.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/DayRepository.java
  src/main/java/com/cosain/trilo/trip/command/domain/vo/ScheduleIndex.java
  src/main/java/com/cosain/trilo/trip/command/presentation/schedule/ScheduleMoveController.java
  src/main/java/com/cosain/trilo/trip/command/presentation/schedule/dto/ScheduleCreateRequest.java
  src/main/java/com/cosain/trilo/trip/command/presentation/schedule/dto/ScheduleMoveRequest.java
  src/main/java/com/cosain/trilo/trip/command/presentation/schedule/dto/ScheduleMoveResponse.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/schedule/ScheduleMoveServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/entity/TripTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/DayRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/vo/ScheduleIndexTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/schedule/ScheduleMoveControllerTest.java
Labels: ⚙️ FEAT

#59 [TRL-243] refactor: 계층간 의존성 분리 및 DTO 컨벤션 적용
  src/main/java/com/cosain/trilo/trip/query/application/dto/TripPageResult.java
  src/main/java/com/cosain/trilo/trip/query/application/dto/TripResult.java
  src/main/java/com/cosain/trilo/trip/query/application/service/TripDetailSearchService.java
  src/main/java/com/cosain/trilo/trip/query/application/service/TripListSearchService.java
  src/main/java/com/cosain/trilo/trip/query/application/usecase/TripDetailSearchUseCase.java
  src/main/java/com/cosain/trilo/trip/query/application/usecase/TripListSearchUseCase.java
  src/main/java/com/cosain/trilo/trip/query/domain/dto/TripDto.java
  src/main/java/com/cosain/trilo/trip/query/domain/repository/TripQueryRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/trip/TripQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/SingleTripQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/TripperTripListQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/dto/TripDetailResponse.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/dto/TripPageResponse.java
  src/test/java/com/cosain/trilo/unit/trip/query/application/TripDetailSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/application/TripListSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/infra/repository/TripQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/trip/SingleTripQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/trip/TripperTripListQueryControllerTest.java
Labels: 🚀 REFACTOR

#62 [TRL-240] feat: 쿼리 카운터 구현
  src/main/java/com/cosain/trilo/common/logging/query/ConnectionProxyHandler.java
  src/main/java/com/cosain/trilo/common/logging/query/DataSourceAspect.java
  src/main/java/com/cosain/trilo/common/logging/query/PreparedStatementProxyHandler.java
  src/main/java/com/cosain/trilo/common/logging/query/QueryCountInterceptor.java
  src/main/java/com/cosain/trilo/common/logging/query/QueryCounter.java
  src/main/java/com/cosain/trilo/config/WebConfig.java
  src/test/java/com/cosain/trilo/common/logging/query/ConnectionProxyHandlerTest.java
  src/test/java/com/cosain/trilo/common/logging/query/DataSourceAspectTest.java
  src/test/java/com/cosain/trilo/common/logging/query/PreparedStatementProxyHandlerTest.java
  src/test/java/com/cosain/trilo/common/logging/query/QueryCounterTest.java
  src/test/java/com/cosain/trilo/support/RestControllerTest.java
Labels: ⚙️ FEAT

#61 [TRL-246] feat: 여행 기간 변경시, 삭제되는 Day의 일정들을 임시보관함으로 이동
  src/main/java/com/cosain/trilo/trip/command/application/service/TripUpdateService.java
  src/main/java/com/cosain/trilo/trip/command/domain/dto/ChangeTripPeriodResult.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/DayRepository.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/ScheduleRepository.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/TripUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/entity/TripTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/DayRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/ScheduleRepositoryTest.java
Labels: ⚙️ FEAT

#65 [TRL-271] feat: 단일 예외 API 사양 변경(코드, 메시지, 상세)
  src/main/java/com/cosain/trilo/common/dto/BasicErrorResponse.java
  src/main/java/com/cosain/trilo/common/dto/ErrorResponse.java
  src/main/java/com/cosain/trilo/common/exception/CustomException.java
  src/main/java/com/cosain/trilo/common/exception/NotExistRefreshTokenException.java
  src/main/java/com/cosain/trilo/common/exception/NotImplementedException.java
  src/main/java/com/cosain/trilo/common/exception/NotSupportClientIdException.java
  src/main/java/com/cosain/trilo/common/exception/NotValidTokenException.java
  src/main/java/com/cosain/trilo/common/exception/TokenAuthenticationFilterException.java
  src/main/java/com/cosain/trilo/common/exception/UserNotFoundException.java
  src/main/java/com/cosain/trilo/config/exception/ExceptionAdvice.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/DayNotFoundException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoScheduleCreateAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoScheduleDeleteAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoScheduleMoveAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoScheduleUpdateAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoTripDeleteAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoTripUpdateAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/ScheduleNotFoundException.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/TripNotFoundException.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/EmptyPeriodUpdateException.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/InvalidCoordinateException.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/InvalidPeriodException.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/InvalidScheduleMoveTargetOrderException.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/InvalidTripDayException.java
  src/main/java/com/cosain/trilo/trip/query/application/exception/NoTripDetailSearchAuthorityException.java
  src/main/java/com/cosain/trilo/trip/query/application/exception/ScheduleNotFoundException.java
  src/main/java/com/cosain/trilo/trip/query/application/exception/TripNotFoundException.java
  src/main/java/com/cosain/trilo/trip/query/application/exception/TripperNotFoundException.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/schedule/ScheduleCreateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/schedule/ScheduleDeleteControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/schedule/ScheduleMoveControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/schedule/ScheduleUpdateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/trip/TripCreateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/trip/TripDeleteControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/trip/TripUpdateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/day/SingleDayQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/day/TripDayListQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/schedule/SingleScheduleQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/trip/SingleTripQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/trip/TripTemporaryStorageQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/trip/TripperTripListQueryControllerTest.java
Labels: ⚙️ FEAT

#64 [TRL-154] feat: Day 단건 조회 API 구현
  src/main/java/com/cosain/trilo/config/JpaConfig.java
  src/main/java/com/cosain/trilo/config/QueryDslConfig.java
  src/main/java/com/cosain/trilo/trip/query/application/exception/DayNotFoundException.java
  src/main/java/com/cosain/trilo/trip/query/application/service/DaySearchService.java
  src/main/java/com/cosain/trilo/trip/query/application/usecase/DaySearchUseCase.java
  src/main/java/com/cosain/trilo/trip/query/domain/repository/DayQueryRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/dto/DayScheduleDetail.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/day/DayQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/day/jpa/DayQueryJpaRepository.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/day/jpa/DayQueryJpaRepositoryCustom.java
  src/main/java/com/cosain/trilo/trip/query/infra/repository/day/jpa/DayQueryJpaRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/query/presentation/day/SingleDayQueryController.java
  src/test/java/com/cosain/trilo/config/QueryDslConfig.java
  src/test/java/com/cosain/trilo/support/RepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/application/DaySearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/infra/repository/DayScheduleQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/api/day/SingleDayQueryControllerTest.java
Labels: ⚙️ FEAT

#72 [TRL-279] docs: API 문서 리팩토링
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/auth/presentation/docs/AuthRestControllerDocsTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/docs/TripCreateControllerDocsTest.java
Labels: 📃 DOCS

#73 refactor: 일정 요약 정보 응답 DTO 구조화
  src/main/java/com/cosain/trilo/trip/infra/dto/Coordinate.java
  src/main/java/com/cosain/trilo/trip/infra/dto/DayScheduleDetail.java
  src/main/java/com/cosain/trilo/trip/infra/dto/ScheduleSummary.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/jpa/DayQueryJpaRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/infra/repository/schedule/jpa/ScheduleQueryJpaRepositoryImpl.java
  src/test/java/com/cosain/trilo/unit/trip/application/day/query/DaySearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/DayScheduleQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/SingleDayQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/TripTemporaryStorageQueryControllerTest.java
Labels: 🚀 REFACTOR

#74 [TRL-282] refactor: 일정 상세 정보 응답 DTO 구조화
  src/main/java/com/cosain/trilo/trip/application/schedule/query/usecase/dto/ScheduleResult.java
  src/main/java/com/cosain/trilo/trip/domain/dto/ScheduleDto.java
  src/main/java/com/cosain/trilo/trip/infra/dto/ScheduleDetail.java
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/query/service/ScheduleDetailSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/ScheduleQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/query/SingleScheduleQueryControllerTest.java
Labels: 🚀 REFACTOR
