Repository teamCoSaIn/trilo-be, pull requests merged in 2023-04, with the labels that each got.

#31 [TRL-169] feat: 예외 API 표준화
  src/main/java/com/cosain/trilo/common/dto/ErrorResponse.java
  src/main/java/com/cosain/trilo/config/exception/ExceptionAdvice.java
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
  src/main/java/com/cosain/trilo/config/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/cosain/trilo/config/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/cosain/trilo/config/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/cosain/trilo/config/security/util/SendErrorUtil.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/scheduleplace/SchedulePlaceDeleteController.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/scheduleplace/SchedulePlaceUpdateController.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripCreateController.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripDeleteController.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripUpdateController.java
  src/main/java/com/cosain/trilo/trip/query/adapter/in/api/schedule/SingleScheduleQueryController.java
  src/main/java/com/cosain/trilo/trip/query/adapter/in/api/schedule/TripScheduleListQueryController.java
  src/main/java/com/cosain/trilo/trip/query/adapter/in/api/scheduleplace/SingleSchedulePlaceQueryController.java
  src/main/java/com/cosain/trilo/trip/query/adapter/in/api/trip/SingleTripQueryController.java
  src/main/java/com/cosain/trilo/trip/query/adapter/in/api/trip/TripTemporaryStorageQueryController.java
  src/main/java/com/cosain/trilo/trip/query/adapter/in/api/trip/TripperTripListQueryController.java
  src/main/java/lombok.config
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/config/MessageSourceTestConfig.java
  src/test/java/com/cosain/trilo/config/property/sourcefactory/YamlPropertySourceFactory.java
  src/test/java/com/cosain/trilo/support/RestControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/adapter/in/api/scheduleplace/SchedulePlaceDeleteControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/adapter/in/api/scheduleplace/SchedulePlaceUpdateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/adapter/in/api/trip/TripCreateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/adapter/in/api/trip/TripDeleteControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/adapter/in/api/trip/TripUpdateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/adapter/in/api/schedule/SingleScheduleQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/adapter/in/api/schedule/TripScheduleListQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/adapter/in/api/scheduleplace/SingleSchedulePlaceQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/adapter/in/api/trip/SingleTripQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/adapter/in/api/trip/TripTemporaryStorageQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/adapter/in/api/trip/TripperTripListQueryControllerTest.java
Labels: ⚙️ FEAT

#32 [TRL-165] feat: 컨트롤러에서 사용자 인증 정보 가져오기 기능 추가
  src/main/java/com/cosain/trilo/common/LoginUser.java
  src/main/java/com/cosain/trilo/config/security/dto/UserPrincipal.java
Labels: ⚙️ FEAT

#33 [TRL-176] chore: 여행 관련 명령 컨트롤러 패키지를 레이어드 아키텍처에 맞게 이동
  src/main/java/com/cosain/trilo/trip/command/presentation/scheduleplace/SchedulePlaceDeleteController.java
  src/main/java/com/cosain/trilo/trip/command/presentation/scheduleplace/SchedulePlaceUpdateController.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/TripCreateController.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/TripDeleteController.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/TripUpdateController.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/scheduleplace/SchedulePlaceDeleteControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/scheduleplace/SchedulePlaceUpdateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/trip/TripCreateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/trip/TripDeleteControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/trip/TripUpdateControllerTest.java
Labels: 🌸 STYLE, 🖋 CHORE

#34 [TRL-175] chore: 여행 관련 조회 컨트롤러 패키지를 레이어드 아키텍처에 맞게 이동
  src/main/java/com/cosain/trilo/trip/query/presentation/schedule/SingleScheduleQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/schedule/TripScheduleListQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/scheduleplace/SingleSchedulePlaceQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/SingleTripQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/TripTemporaryStorageQueryController.java
  src/main/java/com/cosain/trilo/trip/query/presentation/trip/TripperTripListQueryController.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/schedule/SingleScheduleQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/schedule/TripScheduleListQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/scheduleplace/SingleSchedulePlaceQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/trip/SingleTripQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/trip/TripTemporaryStorageQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/query/presentation/trip/TripperTripListQueryControllerTest.java
Labels: 🌸 STYLE, 🖋 CHORE

#35 [TRL-120] feat: 여행 생성 API 구현
  src/main/java/com/cosain/trilo/trip/command/application/command/TripCreateCommand.java
  src/main/java/com/cosain/trilo/trip/command/application/service/TripCreateService.java
  src/main/java/com/cosain/trilo/trip/command/application/usecase/TripCreateUseCase.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Trip.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/TripRepository.java
  src/main/java/com/cosain/trilo/trip/command/domain/vo/TripPeriod.java
  src/main/java/com/cosain/trilo/trip/command/domain/vo/TripStatus.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/TripCreateController.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/dto/TripCreateRequest.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/dto/TripCreateResponse.java
  src/test/java/com/cosain/trilo/support/RestControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/TripCreateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/entity/TripTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/TripRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/trip/TripCreateControllerTest.java
Labels: ⚙️ FEAT

#37 [TRL-164] docs: 인증 인가 관련 API 문서화
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
Labels: 📃 DOCS

#38 [TRL-204] fix: DB 테이블 생성 안되는 문제 해결
  src/main/java/com/cosain/trilo/config/JpaConfig.java
  src/main/java/com/cosain/trilo/config/RedisConfig.java
Labels: 🔨 FIX

#39 [TRL-203] fix: Spring Security RequestMatcher 오류 수정
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
Labels: 🔨 FIX

#40 [TRL-123] feat: 여행 수정 API 구현
  src/main/java/com/cosain/trilo/trip/command/application/command/TripUpdateCommand.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/TripNotFoundException.java
  src/main/java/com/cosain/trilo/trip/command/application/service/TripUpdateService.java
  src/main/java/com/cosain/trilo/trip/command/application/usecase/TripUpdateUseCase.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Day.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Trip.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/DayRepository.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/TripRepository.java
  src/main/java/com/cosain/trilo/trip/command/domain/vo/TripPeriod.java
  src/main/java/com/cosain/trilo/trip/command/domain/vo/TripStatus.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/TripUpdateController.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/dto/TripUpdateRequest.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/dto/TripUpdateResponse.java
  src/test/java/com/cosain/trilo/fixture/TripFixture.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/TripUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/entity/TripTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/DayRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/TripRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/trip/TripUpdateControllerTest.java
Labels: 📃 DOCS, ⚙️ FEAT

#43 [TRL-211] test: TripFixture 에 검증 로직 추가 및 구분을 위한 메서드 명 변경
  src/test/java/com/cosain/trilo/fixture/TripFixture.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/TripUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/entity/TripTest.java
Labels: 🚀 REFACTOR, 💯 TEST

#44 [TRL-209] docs: 여행 생성 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/docs/trip/TripCreateControllerDocsTest.java
Labels: 📃 DOCS, 💯 TEST

#45 [TRL-210] docs: 여행 수정 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/docs/trip/TripUpdateControllerDocsTest.java
Labels: 📃 DOCS, 💯 TEST

#46 [TRL-206] refactor: 여행 수정 기능 리팩터링
  src/main/java/com/cosain/trilo/trip/command/application/command/TripUpdateCommand.java
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoTripUpdateAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/service/TripUpdateService.java
  src/main/java/com/cosain/trilo/trip/command/domain/dto/ChangeTripPeriodResult.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Day.java
  src/main/java/com/cosain/trilo/trip/command/domain/entity/Trip.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/EmptyPeriodUpdateException.java
  src/main/java/com/cosain/trilo/trip/command/domain/exception/InvalidPeriodException.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/TripRepository.java
  src/main/java/com/cosain/trilo/trip/command/domain/vo/TripPeriod.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/dto/TripUpdateRequest.java
  src/test/java/com/cosain/trilo/fixture/TripFixture.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/TripUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/entity/DayTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/entity/TripTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/TripRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/vo/TripPeriodTest.java
  src/test/resources/application.yml
Labels: 🚀 REFACTOR, 💯 TEST

#48 [TRL-122] feat: 여행 삭제 API 구현
  src/main/java/com/cosain/trilo/trip/command/application/exception/NoTripDeleteAuthorityException.java
  src/main/java/com/cosain/trilo/trip/command/application/service/TripDeleteService.java
  src/main/java/com/cosain/trilo/trip/command/application/usecase/TripDeleteUseCase.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/DayRepository.java
  src/main/java/com/cosain/trilo/trip/command/domain/repository/ScheduleRepository.java
  src/main/java/com/cosain/trilo/trip/command/presentation/trip/TripDeleteController.java
  src/test/java/com/cosain/trilo/unit/trip/command/application/service/TripDeleteServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/DayRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/ScheduleRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/domain/repository/TripRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/command/preesentation/api/trip/TripDeleteControllerTest.java
Labels: ⚙️ FEAT
