Repository teamCoSaIn/trilo-be, pull requests merged in 2023-06, with the labels that each got.

#75 [TRL-287] docs: 여행 생성 API 문서 구조 변경
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/docs/TripCreateControllerDocsTest.java
  src/test/resources/org/springframework/restdocs/templates/path-parametes.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 📃 DOCS

#77 [TRL-289] fix: OAuth2 로그인 관련 인증 오류 발생 문제 해결
  src/main/java/com/cosain/trilo/config/security/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
  src/main/java/com/cosain/trilo/config/security/handler/OAuthSuccessHandler.java
  src/main/java/com/cosain/trilo/config/security/util/CookieUtil.java
  src/test/java/com/cosain/trilo/unit/security/OAuth2LoginTest.java
Labels: 🔨 FIX

#78 [TRL-290] fix: CORS 관련 문제 해결
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
Labels: 🔨 FIX

#79 [TRL-253] docs: 여행 단건 조회 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/SingleTripQueryControllerDocsTest.java
Labels: 📃 DOCS

#80 [TRL-254] docs: 일정 단건 조회 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/query/docs/SingleScheduleQueryControllerDocsTest.java
Labels: 📃 DOCS

#81 [TRL-291] fix: OAuth2 성공 시 토큰과 함께 리다이렉트 하도록 변경
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/config/security/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/cosain/trilo/config/security/handler/OAuthSuccessHandler.java
  src/main/java/com/cosain/trilo/config/security/util/CookieUtil.java
  src/test/java/com/cosain/trilo/unit/security/OAuth2LoginTest.java
Labels: 🔨 FIX

#82 [TRL-216] docs: 여행 삭제 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/TripDeleteControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/docs/TripDeleteControllerDocsTest.java
Labels: 📃 DOCS

#84 [TRL-294] docs: Day 단건 조회 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/docs/SingleDayQueryControllerDocsTest.java
Labels: 📃 DOCS

#85 [TRL-296] feat: 일정 생성 API 사양 수정 - 좌표를 객체로 전달
  src/main/java/com/cosain/trilo/trip/application/schedule/command/usecase/dto/factory/ScheduleCreateCommandFactory.java
  src/main/java/com/cosain/trilo/trip/presentation/exception/NullRequestCoordinateException.java
  src/main/java/com/cosain/trilo/trip/presentation/schedule/command/ScheduleCreateController.java
  src/main/java/com/cosain/trilo/trip/presentation/schedule/command/dto/request/RequestCoordinate.java
  src/main/java/com/cosain/trilo/trip/presentation/schedule/command/dto/request/ScheduleCreateRequest.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/dto/factory/ScheduleCreateCommandFactoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/command/ScheduleCreateControllerTest.java
Labels: ⚙️ FEAT

#87 [TRL-295] OAuth2 로그인 기능 구현 - KAKAO
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/auth/application/AuthService.java
  src/main/java/com/cosain/trilo/auth/application/dto/LoginResult.java
  src/main/java/com/cosain/trilo/auth/infra/OAuthClient.java
  src/main/java/com/cosain/trilo/auth/infra/OAuthProfileDto.java
  src/main/java/com/cosain/trilo/auth/infra/TokenProvider.java
  src/main/java/com/cosain/trilo/auth/infra/jwt/JwtTokenProvider.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/kakao/KakaoClient.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/kakao/dto/KakaoProfileResponse.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/kakao/dto/KakaoTokenRequest.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/kakao/dto/KakaoTokenResponse.java
  src/main/java/com/cosain/trilo/auth/presentation/AuthRestController.java
  src/main/java/com/cosain/trilo/auth/presentation/dto/OauthLoginRequest.java
  src/main/java/com/cosain/trilo/config/security/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
  src/main/java/com/cosain/trilo/config/security/dto/AuthUriResponse.java
  src/main/java/com/cosain/trilo/config/security/dto/OAuthAttributes.java
  src/main/java/com/cosain/trilo/config/security/handler/OAuthSuccessHandler.java
  src/main/java/com/cosain/trilo/config/security/service/CustomOAuthService.java
  src/main/java/com/cosain/trilo/config/security/util/CookieUtil.java
  src/main/java/com/cosain/trilo/user/domain/User.java
  src/test/java/com/cosain/trilo/unit/auth/application/AuthServiceTest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/api/AuthRestControllerTest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/docs/AuthRestControllerDocsTest.java
  src/test/java/com/cosain/trilo/unit/security/OAuth2LoginTest.java
  src/test/resources/application.yml
Labels: ⚙️ FEAT

#88 [TRL-215] docs: 일정 수정 API 문서화
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/domain/entity/Schedule.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/command/docs/ScheduleUpdateControllerDocsTest.java
Labels: 📃 DOCS

#89 [TRL-217] docs: 일정 삭제 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/command/docs/ScheduleDeleteControllerDocsTest.java
Labels: 📃 DOCS

#90 [TRL-297] chore: Allowed-Origins 구체화
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
Labels: 🔨 FIX

#91 [TRL-252] docs: 임시보관함 조회 API 문서화
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/presentation/trip/query/TripTemporaryStorageQueryController.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/TripTemporaryStorageQueryControllerDocsTest.java
Labels: 📃 DOCS

#92 [TRL-255] docs: 사용자 여행 목록 조회 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/TripperTripListQueryControllerDocsTest.java
Labels: 📃 DOCS

#93 [TRL-300] docs: API 문서에 누락된 페이징 정보 추가
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/TripTemporaryStorageQueryControllerDocsTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/TripperTripListQueryControllerDocsTest.java
Labels: 📃 DOCS

#94 [TRL-155] feat: 여행의 Day 목록 조회 API 구현
  src/main/java/com/cosain/trilo/trip/application/day/query/service/DaySearchService.java
  src/main/java/com/cosain/trilo/trip/application/day/query/usecase/DaySearchUseCase.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/DayQueryRepository.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/DayQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/jpa/DayQueryJpaRepositoryCustom.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/jpa/DayQueryJpaRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/presentation/day/query/TripDayListQueryController.java
  src/main/java/com/cosain/trilo/trip/presentation/day/query/dto/DayListResponse.java
  src/test/java/com/cosain/trilo/support/RepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/day/query/DaySearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/DayQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/DayScheduleQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/TripDayListQueryControllerTest.java
Labels: ⚙️ FEAT

#95 [TRL-298] feat: 일정 이동 API - 일정 개수 제약 조건 반영
  src/main/java/com/cosain/trilo/trip/application/schedule/command/service/ScheduleMoveService.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/service/ScheduleMoveServiceTest.java
Labels: ⚙️ FEAT

#96 [TRL-256] docs: 여행의 Day 목록 조회 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/docs/TripDayListQueryControllerDocsTest.java
Labels: 📃 DOCS

#97 [TRL-303] docs: API 문서 구조 리팩토링
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/auth/presentation/docs/AuthRestControllerDocsTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/docs/SingleDayQueryControllerDocsTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/docs/TripDayListQueryControllerDocsTest.java
Labels: 📃 DOCS

#98 [TRL-299] docs: 일정 이동 API 문서화
  src/docs/asciidoc/imgs/schedule-move1.jpg
  src/docs/asciidoc/imgs/schedule-move2.jpg
  src/docs/asciidoc/imgs/schedule-move3.jpg
  src/docs/asciidoc/imgs/schedule-move4.jpg
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/command/docs/ScheduleMoveControllerDocsTest.java
Labels: 📃 DOCS

#99 [TRL-304] fix: API 문서에서 이미지 안보이는 문제 해결
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/imgs/schedule-move1.jpg
  src/main/resources/static/docs/imgs/schedule-move2.jpg
  src/main/resources/static/docs/imgs/schedule-move3.jpg
  src/main/resources/static/docs/imgs/schedule-move4.jpg
Labels: 🔨 FIX

#100 [TRL-305] feat: 일정 - 시작/종료 속성 추가 및 API 반영
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/application/schedule/command/service/ScheduleUpdateService.java
  src/main/java/com/cosain/trilo/trip/application/schedule/command/usecase/dto/ScheduleUpdateCommand.java
  src/main/java/com/cosain/trilo/trip/application/schedule/command/usecase/dto/factory/ScheduleUpdateCommandFactory.java
  src/main/java/com/cosain/trilo/trip/domain/entity/Schedule.java
  src/main/java/com/cosain/trilo/trip/domain/vo/ScheduleTime.java
  src/main/java/com/cosain/trilo/trip/presentation/schedule/command/ScheduleUpdateController.java
  src/main/java/com/cosain/trilo/trip/presentation/schedule/command/dto/request/ScheduleUpdateRequest.java
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/dto/factory/ScheduleUpdateCommandFactoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/service/ScheduleUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/command/ScheduleUpdateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/command/docs/ScheduleUpdateControllerDocsTest.java
Labels: ⚙️ FEAT

#101 [TRL-307] feat: DayColor 속성 추가, 여행 생성 시점에 Day가 랜덤 색상을 가지도록 반영
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/domain/entity/Day.java
  src/main/java/com/cosain/trilo/trip/domain/entity/Trip.java
  src/main/java/com/cosain/trilo/trip/domain/exception/InvalidDayColorNameException.java
  src/main/java/com/cosain/trilo/trip/domain/vo/DayColor.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/fixture/TripFixture.java
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/service/ScheduleCreateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/service/ScheduleDeleteServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/entity/DayTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/entity/TripTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/repository/DayRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/repository/ScheduleRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/repository/TripRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/vo/DayColorTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/DayQueryRepositoryTest.java
Labels: 📃 DOCS, ⚙️ FEAT, 💯 TEST

#102 [TRL-302] feat: OAuth2 로그인 기능 구현 - NAVER
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/auth/application/AuthService.java
  src/main/java/com/cosain/trilo/auth/application/OAuthProfileRequestService.java
  src/main/java/com/cosain/trilo/auth/application/dto/KakaoLoginParams.java
  src/main/java/com/cosain/trilo/auth/application/dto/NaverLoginParams.java
  src/main/java/com/cosain/trilo/auth/application/dto/OAuthLoginParams.java
  src/main/java/com/cosain/trilo/auth/infra/OAuthClient.java
  src/main/java/com/cosain/trilo/auth/infra/OAuthProfileDto.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/kakao/KakaoClient.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/naver/NaverClient.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/naver/dto/NaverInfoResponse.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/naver/dto/NaverTokenResponse.java
  src/main/java/com/cosain/trilo/auth/presentation/AuthRestController.java
  src/main/java/com/cosain/trilo/auth/presentation/dto/KakaoOAuthLoginRequest.java
  src/main/java/com/cosain/trilo/auth/presentation/dto/NaverOAuthLoginRequest.java
  src/main/java/com/cosain/trilo/config/RestTemplateConfig.java
  src/test/java/com/cosain/trilo/unit/auth/application/AuthServiceTest.java
  src/test/java/com/cosain/trilo/unit/auth/application/OAuthProfileRequestServiceTest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/api/AuthRestControllerTest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/docs/AuthRestControllerDocsTest.java
  src/test/resources/application.yml
Labels: ⚙️ FEAT

#103 [TRL-310] feat: Day의 DayColor 수정 API 구현
  src/main/java/com/cosain/trilo/trip/application/day/command/dto/DayColorUpdateCommand.java
  src/main/java/com/cosain/trilo/trip/application/day/command/dto/factory/DayColorUpdateCommandFactory.java
  src/main/java/com/cosain/trilo/trip/application/day/command/service/DayColorUpdateService.java
  src/main/java/com/cosain/trilo/trip/application/day/command/usecase/DayColorUpdateUseCase.java
  src/main/java/com/cosain/trilo/trip/application/exception/NoDayUpdateAuthorityException.java
  src/main/java/com/cosain/trilo/trip/domain/entity/Day.java
  src/main/java/com/cosain/trilo/trip/presentation/day/command/DayColorUpdateController.java
  src/main/java/com/cosain/trilo/trip/presentation/day/command/dto/DayColorUpdateRequest.java
  src/main/java/com/cosain/trilo/trip/presentation/day/command/dto/DayColorUpdateResponse.java
  src/main/java/com/cosain/trilo/trip/presentation/trip/command/TripUpdateController.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/unit/trip/application/day/command/dto/factory/DayColorUpdateCommandFactoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/day/command/service/DayColorUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/entity/DayTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/command/DayColorUpdateControllerTest.java
Labels: 📃 DOCS, ⚙️ FEAT, 💯 TEST

#104 [TRL-312] docs: Day의 DayColor 수정 API 문서화
  src/docs/asciidoc/index.adoc
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/command/docs/DayColorUpdateControllerDocsTest.java
Labels: 📃 DOCS

#105 [TRL-309, TRL-313] feat: 여행 제목 수정 API 분리 및 문서화
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/application/trip/command/service/TripTitleUpdateService.java
  src/main/java/com/cosain/trilo/trip/application/trip/command/usecase/TripTitleUpdateUseCase.java
  src/main/java/com/cosain/trilo/trip/application/trip/command/usecase/dto/TripTitleUpdateCommand.java
  src/main/java/com/cosain/trilo/trip/application/trip/command/usecase/dto/factory/TripTitleUpdateCommandFactory.java
  src/main/java/com/cosain/trilo/trip/presentation/trip/command/TripTitleUpdateController.java
  src/main/java/com/cosain/trilo/trip/presentation/trip/command/dto/request/TripTitleUpdateRequest.java
  src/main/java/com/cosain/trilo/trip/presentation/trip/command/dto/request/TripTitleUpdateResponse.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/command/dto/factory/TripTitleUpdateCommandFactoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/command/service/TripTitleUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/TripTitleUpdateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/docs/TripTitleUpdateControllerDocsTest.java
Labels: 📃 DOCS, ⚙️ FEAT, 💯 TEST

#107 [TRL-315] fix: @RequestBody 검증 시 @Valid 사용하도록 수정
  src/main/java/com/cosain/trilo/auth/presentation/AuthRestController.java
Labels: 🔨 FIX

#108 [TRL-316] fix: 카카오 로그인 응답 데이터 객체 -> ResponseEntity
  src/main/java/com/cosain/trilo/auth/presentation/AuthRestController.java
Labels: 🔨 FIX

#109 [TRL-301] feat: OAuth2 로그인 기능 구현 - GOOGLE
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/auth/application/dto/GoogleLoginParams.java
  src/main/java/com/cosain/trilo/auth/infra/OAuthProfileDto.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/google/GoogleClient.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/google/dto/GoogleInfoResponse.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/google/dto/GoogleTokenResponse.java
  src/main/java/com/cosain/trilo/auth/presentation/AuthRestController.java
  src/main/java/com/cosain/trilo/auth/presentation/dto/GoogleOAuthLoginRequest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/api/AuthRestControllerTest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/docs/AuthRestControllerDocsTest.java
  src/test/resources/application.yml
Labels: ⚙️ FEAT

#110 [TRL-283] refactor: QueryRepository 의존 관계 및 구조 개선
  src/main/java/com/cosain/trilo/config/JpaConfig.java
  src/main/java/com/cosain/trilo/trip/application/day/query/service/DaySearchService.java
  src/main/java/com/cosain/trilo/trip/application/schedule/query/service/ScheduleDetailSearchService.java
  src/main/java/com/cosain/trilo/trip/application/trip/query/service/TripDetailSearchService.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/DayQueryRepository.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/DayQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/jpa/DayQueryJpaRepository.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/jpa/DayQueryJpaRepositoryCustom.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/jpa/DayQueryJpaRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/infra/repository/schedule/ScheduleQueryRepository.java
  src/main/java/com/cosain/trilo/trip/infra/repository/schedule/ScheduleQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/infra/repository/schedule/jpa/ScheduleQueryJpaRepository.java
  src/main/java/com/cosain/trilo/trip/infra/repository/schedule/jpa/ScheduleQueryJpaRepositoryCustom.java
  src/main/java/com/cosain/trilo/trip/infra/repository/schedule/jpa/ScheduleQueryJpaRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/infra/repository/trip/TripQueryRepository.java
  src/main/java/com/cosain/trilo/trip/infra/repository/trip/TripQueryRepositoryImpl.java
  src/main/java/com/cosain/trilo/trip/infra/repository/trip/jpa/TripQueryJpaRepository.java
  src/main/java/com/cosain/trilo/trip/infra/repository/trip/jpa/TripQueryJpaRepositoryCustom.java
  src/main/java/com/cosain/trilo/trip/infra/repository/trip/jpa/TripQueryJpaRepositoryImpl.java
  src/test/java/com/cosain/trilo/support/RepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/day/query/DaySearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/query/service/ScheduleDetailSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/query/service/TemporarySearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/query/service/TripDetailSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/ScheduleQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/TripQueryRepositoryTest.java
Labels: 🚀 REFACTOR

#113 [TRL-319] fix: 임시보관함 목록 페이징 조회 시 커서 기반 페이지네이션 방식으로 조회하도록 변경
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/application/trip/query/service/TemporarySearchService.java
  src/main/java/com/cosain/trilo/trip/application/trip/query/usecase/TemporarySearchUseCase.java
  src/main/java/com/cosain/trilo/trip/infra/repository/schedule/ScheduleQueryRepository.java
  src/main/java/com/cosain/trilo/trip/presentation/trip/query/TripTemporaryStorageQueryController.java
  src/main/java/com/cosain/trilo/trip/presentation/trip/query/dto/request/TempSchedulePageCondition.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/query/service/TemporarySearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/ScheduleQueryRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/TripTemporaryStorageQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/TripTemporaryStorageQueryControllerDocsTest.java
Labels: 🔨 FIX

#115 [TRL-325] fix: Auth 응답에 사용자 ID도 포함하도록 수정
  src/main/java/com/cosain/trilo/auth/application/AuthService.java
  src/main/java/com/cosain/trilo/auth/application/dto/LoginResult.java
  src/main/java/com/cosain/trilo/auth/application/dto/ReIssueAccessTokenResult.java
  src/main/java/com/cosain/trilo/auth/infra/oauth/kakao/dto/KakaoTokenRequest.java
  src/main/java/com/cosain/trilo/auth/presentation/AuthRestController.java
  src/main/java/com/cosain/trilo/auth/presentation/dto/AuthResponse.java
  src/test/java/com/cosain/trilo/unit/auth/application/AuthServiceTest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/api/AuthRestControllerTest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/docs/AuthRestControllerDocsTest.java
Labels: 🔨 FIX

#116 [TRL-319] fix: 사용자 여행 목록 조회 시 여행 ID 를 id 가 아닌 tripId 로 반환
  src/main/java/com/cosain/trilo/trip/infra/dto/TripSummary.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/TripperTripListQueryControllerDocsTest.java
Labels: 🔨 FIX

#117 [TRL-331] fix: Auth 응답에서 사용자 ID 를 userId 로 반환하도록 수정
  src/main/java/com/cosain/trilo/auth/application/AuthService.java
  src/main/java/com/cosain/trilo/auth/application/dto/ReIssueAccessTokenResult.java
  src/main/java/com/cosain/trilo/auth/presentation/dto/AuthResponse.java
  src/test/java/com/cosain/trilo/unit/auth/application/AuthServiceTest.java
  src/test/java/com/cosain/trilo/unit/auth/presentation/docs/AuthRestControllerDocsTest.java
Labels: 🔨 FIX

#118 [TRL-332] docs: 일정 조회 API 문서 scheduleId 설명 수정
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/query/docs/SingleScheduleQueryControllerDocsTest.java
Labels: 📃 DOCS

#112 [TRL-323, TRL-324] feat: 여행 이미지 수정 API 구현 및 문서화
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/common/exception/EmptyFileException.java
  src/main/java/com/cosain/trilo/common/exception/NoFileExtensionException.java
  src/main/java/com/cosain/trilo/common/exception/NoFileNameException.java
  src/main/java/com/cosain/trilo/common/exception/NotImageFileException.java
  src/main/java/com/cosain/trilo/common/exception/NotImageFileExtensionException.java
  src/main/java/com/cosain/trilo/common/file/ImageFile.java
  src/main/java/com/cosain/trilo/config/S3Config.java
  src/main/java/com/cosain/trilo/config/exception/ExceptionAdvice.java
  src/main/java/com/cosain/trilo/trip/application/exception/TripImageUploadFailedException.java
  src/main/java/com/cosain/trilo/trip/application/trip/command/service/TripImageUpdateService.java
  src/main/java/com/cosain/trilo/trip/application/trip/command/usecase/TripImageUpdateUseCase.java
  src/main/java/com/cosain/trilo/trip/domain/entity/Trip.java
  src/main/java/com/cosain/trilo/trip/domain/vo/TripImage.java
  src/main/java/com/cosain/trilo/trip/infra/adapter/TripImageOutputAdapter.java
  src/main/java/com/cosain/trilo/trip/presentation/trip/command/TripImageUpdateController.java
  src/main/java/com/cosain/trilo/trip/presentation/trip/command/dto/response/TripImageUpdateResponse.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/common/file/ImageFileTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/command/service/TripImageUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/adapter/TripImageOutputAdapterTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/TripImageUpdateControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/docs/TripImageUpdateControllerDocsTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/command/docs/TripPeriodUpdateControllerDocsTest.java
  src/test/resources/application.yml
  src/test/resources/org/springframework/restdocs/templates/request-parts.snippet
  src/test/resources/testFiles/empty-file.jpg
  src/test/resources/testFiles/no-extension
  src/test/resources/testFiles/no-image.jpg
  src/test/resources/testFiles/not-image-extension.txt
  src/test/resources/testFiles/test-gif-image.gif
  src/test/resources/testFiles/test-jpeg-image.jpeg
  src/test/resources/testFiles/test-jpg-image.jpg
  src/test/resources/testFiles/test-png-image.png
  src/test/resources/testFiles/test-webp-image.webp
Labels: 📃 DOCS, ⚙️ FEAT, 💯 TEST

#119 [TRL-333] feat: 일정 시간 - 디폴트 값, 제약조건 설정 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/domain/entity/Schedule.java
  src/main/java/com/cosain/trilo/trip/domain/exception/InvalidScheduleTimeException.java
  src/main/java/com/cosain/trilo/trip/domain/vo/ScheduleTime.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/dto/factory/ScheduleUpdateCommandFactoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/entity/TripTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/vo/ScheduleTimeTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/command/docs/ScheduleUpdateControllerDocsTest.java
Labels: ⚙️ FEAT, 💯 TEST

#120 [TRL-306] fix: 일정 상세 정보 조회 시 시작 시간, 끝 시간 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/infra/dto/ScheduleDetail.java
  src/main/java/com/cosain/trilo/trip/infra/dto/ScheduleTime.java
  src/main/java/com/cosain/trilo/trip/infra/repository/schedule/ScheduleQueryRepository.java
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/query/service/ScheduleDetailSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/query/service/TemporarySearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/query/SingleScheduleQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/query/docs/SingleScheduleQueryControllerDocsTest.java
Labels: 🔨 FIX

#121 [TRL-347] refactor: 여행 이미지 전체 경로를 가져오는 메서드 분리
  src/main/java/com/cosain/trilo/trip/application/trip/command/service/TripImageUpdateService.java
  src/main/java/com/cosain/trilo/trip/infra/adapter/TripImageOutputAdapter.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/command/service/TripImageUpdateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/infra/adapter/TripImageOutputAdapterTest.java
Labels: 🚀 REFACTOR

#123 [TRL-308] fix: 전체 Day 목록 조회 시 응답에 Color 값(code, name) 추가
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/infra/dto/DayColorDto.java
  src/main/java/com/cosain/trilo/trip/infra/dto/DayScheduleDetail.java
  src/main/java/com/cosain/trilo/trip/infra/repository/day/DayQueryRepository.java
  src/test/java/com/cosain/trilo/unit/trip/application/day/query/DaySearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/SingleDayQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/TripDayListQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/docs/SingleDayQueryControllerDocsTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/day/query/docs/TripDayListQueryControllerDocsTest.java
Labels: 🔨 FIX

#125 [TRL-352] fix: 전체 Day 목록 조회시 Day에 대한 일정이 존재하지 않는 경우에도 모든 인자가 null 인 ScheduleSummary 를 반환하는 문제 해결
  src/main/java/com/cosain/trilo/trip/infra/repository/day/DayQueryRepository.java
  src/test/java/com/cosain/trilo/unit/trip/infra/repository/DayQueryRepositoryTest.java
Labels: 🔨 FIX

#126 [TRL-356] PR 템플릿 등록
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🌸 STYLE

#127 [TRL-350] fix: 사용자 여행 목록 조회 시 각 여행에 대한 이미지 URL 추가
  src/main/java/com/cosain/trilo/trip/application/trip/query/service/TripListSearchService.java
  src/main/java/com/cosain/trilo/trip/infra/dto/TripSummary.java
  src/main/java/com/cosain/trilo/trip/infra/repository/trip/TripQueryRepository.java
  src/test/java/com/cosain/trilo/unit/trip/application/trip/query/service/TripListSearchServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/TripperTripListQueryControllerTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/TripperTripListQueryControllerDocsTest.java
Labels: 🔨 FIX

#131 [TRL-367] fix: 회원 프로필 조회 API 문서 잘못된 파라미터 전달 수정
  src/test/java/com/cosain/trilo/unit/trip/presentation/trip/query/docs/TripperTripListQueryControllerDocsTest.java
  src/test/java/com/cosain/trilo/unit/user/presentation/UserRestControllerDocsTest.java
Labels: 🔨 FIX

#132 [TRL-368] chore: 회원 프로필 조회 기능 명확한 변수명으로 수정 및 예외 코드 수정
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/user/application/UserService.java
  src/main/java/com/cosain/trilo/user/application/exception/UserNotFoundException.java
  src/main/java/com/cosain/trilo/user/presentation/UserRestController.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/unit/user/application/UserServiceTest.java
Labels: 🖋 CHORE

#133 [TRL-378] fix: 일정 본문 크기로 인한 데이터베이스 오류 발생 -> 본문 바이트 제한 수정
  src/main/java/com/cosain/trilo/trip/domain/vo/ScheduleContent.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/dto/factory/ScheduleUpdateCommandFactoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/repository/ScheduleRepositoryTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/vo/ScheduleContentTest.java
  src/test/java/com/cosain/trilo/unit/trip/presentation/schedule/command/docs/ScheduleUpdateControllerDocsTest.java
Labels: ⚙️ FEAT, 🔨 FIX

#134 [TRL-379] feat: 일정을 임시보관함에 생성할 시, 맨 앞에 생성되도록 수정
  src/docs/asciidoc/index.adoc
  src/main/java/com/cosain/trilo/trip/domain/entity/Trip.java
  src/test/java/com/cosain/trilo/unit/trip/application/schedule/command/service/ScheduleCreateServiceTest.java
  src/test/java/com/cosain/trilo/unit/trip/domain/entity/TripTest.java
Labels: ⚙️ FEAT
