Repository teamCoSaIn/trilo-be, pull requests merged in 2023-03, with the labels that each got.

#11 [TRL-131] infra: 설정 파일 외부 분리
  .gitignore
  scripts/run_new_was.sh
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🗽 INFRA

#13 [TRL-143] chore: SpringSecurity 의존성 추가
  build.gradle
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
Labels: 🖋 CHORE

#15 [TRL-113] feat: 로그인 기능 구현
  .github/workflows/build-test.yml
  .github/workflows/deploy-ec2.yml
  build.gradle
  src/main/java/com/cosain/trilo/auth/domain/Token.java
  src/main/java/com/cosain/trilo/auth/domain/TokenRepository.java
  src/main/java/com/cosain/trilo/auth/infra/TokenAnalyzer.java
  src/main/java/com/cosain/trilo/auth/infra/TokenProvider.java
  src/main/java/com/cosain/trilo/auth/infra/jwt/JwtTokenAnalyzer.java
  src/main/java/com/cosain/trilo/auth/infra/jwt/JwtTokenProvider.java
  src/main/java/com/cosain/trilo/common/dto/ErrorResponse.java
  src/main/java/com/cosain/trilo/common/exception/AuthorizationHeaderTypeException.java
  src/main/java/com/cosain/trilo/common/exception/NotSupportClientIdException.java
  src/main/java/com/cosain/trilo/common/exception/TokenAuthenticationFilterException.java
  src/main/java/com/cosain/trilo/common/exception/UserNotFoundException.java
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
  src/main/java/com/cosain/trilo/config/security/dto/OAuthAttributes.java
  src/main/java/com/cosain/trilo/config/security/dto/UserPrincipal.java
  src/main/java/com/cosain/trilo/config/security/filter/ExceptionHandlerFilter.java
  src/main/java/com/cosain/trilo/config/security/filter/TokenAuthenticationFilter.java
  src/main/java/com/cosain/trilo/config/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/cosain/trilo/config/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/cosain/trilo/config/security/handler/OAuthSuccessHandler.java
  src/main/java/com/cosain/trilo/config/security/service/CustomOAuthService.java
  src/main/java/com/cosain/trilo/config/security/util/CookieUtil.java
  src/main/java/com/cosain/trilo/config/security/util/HeaderUtil.java
  src/main/java/com/cosain/trilo/config/security/util/SendErrorUtil.java
  src/main/java/com/cosain/trilo/deploy/DeployController.java
  src/main/java/com/cosain/trilo/user/domain/AuthProvider.java
  src/main/java/com/cosain/trilo/user/domain/Role.java
  src/main/java/com/cosain/trilo/user/domain/User.java
  src/main/java/com/cosain/trilo/user/domain/UserRepository.java
  src/test/java/com/cosain/trilo/auth/application/JwtTokenAnalyzerTest.java
  src/test/java/com/cosain/trilo/auth/application/JwtTokenProviderTest.java
  src/test/java/com/cosain/trilo/auth/domain/TokenRepositoryTest.java
  src/test/java/com/cosain/trilo/deploy/DeployControllerTest.java
  src/test/java/com/cosain/trilo/fixture/UserFixture.java
  src/test/java/com/cosain/trilo/security/OAuth2LoginTest.java
  src/test/java/com/cosain/trilo/support/RestDocsTestSupport.java
  src/test/java/com/cosain/trilo/support/auth/AuthHelper.java
  src/test/java/com/cosain/trilo/user/infra/UserRepositoryTest.java
  src/test/resources/application.yml
Labels: ⚙️ FEAT

#17 [TRL-146] feat: CORS 필터 설정
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
  src/test/resources/application.yml
Labels: ⚙️ FEAT

#18 [TRL-156] feat: 여행 명령 API 엔드포인트 정의
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/scheduleplace/SchedulePlaceDeleteController.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/scheduleplace/SchedulePlaceUpdateController.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripCreateController.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripDeleteController.java
  src/main/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripUpdateController.java
  src/test/java/com/cosain/trilo/trip/command/adapter/in/api/scheduleplace/SchedulePlaceDeleteControllerTest.java
  src/test/java/com/cosain/trilo/trip/command/adapter/in/api/scheduleplace/SchedulePlaceUpdateControllerTest.java
  src/test/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripCreateControllerTest.java
  src/test/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripDeleteControllerTest.java
  src/test/java/com/cosain/trilo/trip/command/adapter/in/api/trip/TripUpdateControllerTest.java
Labels: ⚙️ FEAT

#21 [TRL-161] chore: 로그인 요청 Base URI수정
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
Labels: 🖋 CHORE

#24 [TRL-162] fix: 인증 데이터를 JSON 형식으로 보내도록 수정
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
  src/main/java/com/cosain/trilo/config/security/dto/AuthUriResponse.java
  src/main/java/com/cosain/trilo/config/security/handler/OAuthSuccessHandler.java
  src/test/java/com/cosain/trilo/security/OAuth2LoginTest.java
Labels: 🔨 FIX

#25 [TRL-142] feat: Refresh 토큰 상태 조회 기능 구현
  src/main/java/com/cosain/trilo/auth/application/AuthService.java
  src/main/java/com/cosain/trilo/auth/infra/TokenAnalyzer.java
  src/main/java/com/cosain/trilo/auth/infra/jwt/JwtTokenAnalyzer.java
  src/main/java/com/cosain/trilo/auth/presentation/AuthRestController.java
  src/main/java/com/cosain/trilo/auth/presentation/dto/RefreshTokenStatusResponse.java
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
  src/test/java/com/cosain/trilo/auth/application/AuthServiceTest.java
  src/test/java/com/cosain/trilo/auth/presentation/AuthRestControllerTest.java
Labels: ⚙️ FEAT

#26 [TRL-115] feat: 로그아웃 기능 구현
  src/main/java/com/cosain/trilo/auth/application/AuthService.java
  src/main/java/com/cosain/trilo/auth/domain/LogoutAccessToken.java
  src/main/java/com/cosain/trilo/auth/domain/RefreshToken.java
  src/main/java/com/cosain/trilo/auth/domain/Token.java
  src/main/java/com/cosain/trilo/auth/domain/TokenRepository.java
  src/main/java/com/cosain/trilo/auth/domain/repository/TokenRepository.java
  src/main/java/com/cosain/trilo/auth/infra/TokenAnalyzer.java
  src/main/java/com/cosain/trilo/auth/infra/jwt/JwtTokenAnalyzer.java
  src/main/java/com/cosain/trilo/auth/infra/repository/LogoutAccessTokenRepository.java
  src/main/java/com/cosain/trilo/auth/infra/repository/RefreshTokenRepository.java
  src/main/java/com/cosain/trilo/auth/infra/repository/TokenRepositoryImpl.java
  src/main/java/com/cosain/trilo/auth/presentation/AuthRestController.java
  src/main/java/com/cosain/trilo/config/security/SecurityConfig.java
  src/main/java/com/cosain/trilo/config/security/filter/TokenAuthenticationFilter.java
  src/main/java/com/cosain/trilo/config/security/handler/OAuthSuccessHandler.java
  src/main/java/com/cosain/trilo/config/security/util/HeaderUtil.java
  src/test/java/com/cosain/trilo/auth/application/AuthServiceTest.java
  src/test/java/com/cosain/trilo/auth/application/JwtTokenAnalyzerTest.java
  src/test/java/com/cosain/trilo/auth/domain/TokenRepositoryTest.java
  src/test/java/com/cosain/trilo/auth/infra/repository/TokenRepositoryImplTest.java
  src/test/java/com/cosain/trilo/auth/presentation/AuthRestControllerTest.java
Labels: ⚙️ FEAT

#27 [TRL-167] feat: 메시지, 국제화 설정
  build.gradle
  src/main/java/com/cosain/trilo/config/message/LocaleConfiguration.java
  src/main/java/com/cosain/trilo/config/message/MessageConfiguration.java
  src/main/resources/exceptions/exception.yml
  src/main/resources/exceptions/exception_en.yml
Labels: ⚙️ FEAT
